// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCniRGoso18xeKsaqUfpkEsUUClwrbSXc0',
    appId: '1:1090758221545:web:4a50f8719ee34d03f51a78',
    messagingSenderId: '1090758221545',
    projectId: 'marsgaming-40c0d',
    authDomain: 'marsgaming-40c0d.firebaseapp.com',
    databaseURL: 'https://marsgaming-40c0d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'marsgaming-40c0d.appspot.com',
    measurementId: 'G-NGE1CHRE65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzLaRVvxFhSCKDknNtgzJrv3obKukllW8',
    appId: '1:1090758221545:android:579f5a073bae165bf51a78',
    messagingSenderId: '1090758221545',
    projectId: 'marsgaming-40c0d',
    databaseURL: 'https://marsgaming-40c0d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'marsgaming-40c0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeFa1yIiqoF6qubDrf8bu4RHUi5Y0ks2k',
    appId: '1:1090758221545:ios:ffa8ab5e88f71a24f51a78',
    messagingSenderId: '1090758221545',
    projectId: 'marsgaming-40c0d',
    databaseURL: 'https://marsgaming-40c0d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'marsgaming-40c0d.appspot.com',
    iosClientId: '1090758221545-1c2ibo8r49c25v3l7aploeavag9oqgh5.apps.googleusercontent.com',
    iosBundleId: 'com.marsgaming.marsGaming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeFa1yIiqoF6qubDrf8bu4RHUi5Y0ks2k',
    appId: '1:1090758221545:ios:ffa8ab5e88f71a24f51a78',
    messagingSenderId: '1090758221545',
    projectId: 'marsgaming-40c0d',
    databaseURL: 'https://marsgaming-40c0d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'marsgaming-40c0d.appspot.com',
    iosClientId: '1090758221545-1c2ibo8r49c25v3l7aploeavag9oqgh5.apps.googleusercontent.com',
    iosBundleId: 'com.marsgaming.marsGaming',
  );
}
