// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzypNw6h62u-IOCnyBobMPfBVOzbeez_4',
    appId: '1:873556556575:web:6188e76e2da2f68b1bce2a',
    messagingSenderId: '873556556575',
    projectId: 'crypto-da28a',
    authDomain: 'crypto-da28a.firebaseapp.com',
    databaseURL: 'https://crypto-da28a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crypto-da28a.appspot.com',
    measurementId: 'G-82KNE7CFW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALIhEuN6b1gEzd0BkMIZv--MoRy1ygUq8',
    appId: '1:873556556575:android:d59d5e640e91e0531bce2a',
    messagingSenderId: '873556556575',
    projectId: 'crypto-da28a',
    databaseURL: 'https://crypto-da28a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crypto-da28a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNF5mzM3zslxuj09PqRsr65aSwTz-Npr8',
    appId: '1:873556556575:ios:b4952fdf22d4dcb11bce2a',
    messagingSenderId: '873556556575',
    projectId: 'crypto-da28a',
    databaseURL: 'https://crypto-da28a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crypto-da28a.appspot.com',
    iosClientId: '873556556575-c3m2oh28poi3bpjjp5lf3q6famq119nh.apps.googleusercontent.com',
    iosBundleId: 'com.marsgaming.marsGaming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNF5mzM3zslxuj09PqRsr65aSwTz-Npr8',
    appId: '1:873556556575:ios:b4952fdf22d4dcb11bce2a',
    messagingSenderId: '873556556575',
    projectId: 'crypto-da28a',
    databaseURL: 'https://crypto-da28a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crypto-da28a.appspot.com',
    iosClientId: '873556556575-c3m2oh28poi3bpjjp5lf3q6famq119nh.apps.googleusercontent.com',
    iosBundleId: 'com.marsgaming.marsGaming',
  );
}
